# -*- coding: utf-8 -*-
"""
/***************************************************************************
 landuse_continuity
                                 A QGIS plugin
 Analyze Land-Use Continuity
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-27
        copyright            : (C) 2025 by Xinran Zhang
        email                : xinranzhang0520@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load landuse_continuity class from file landuse_continuity.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .landuse_continuity import landuse_continuity
    return landuse_continuity(iface)
