# -*- coding: utf-8 -*-
"""
/***************************************************************************
 landuse_continuityDialog
                                 A QGIS plugin
 Analyze Land-Use Continuity
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-27
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Xinran Zhang
        email                : xinranzhang0520@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from PyQt5.QtWidgets import QMessageBox
from .analysis import compare_layers
from PyQt5 import uic
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import QgsProject, QgsApplication
from PyQt5 import QtWidgets
from qgis.core import QgsVectorLayer, QgsProject, QgsWkbTypes

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'landuse_continuity_dialog_base.ui'))


class landuse_continuityDialog(QtWidgets.QDialog, FORM_CLASS):
    from qgis.core import QgsVectorLayer, QgsWkbTypes

    def showEvent(self, event):
        super().showEvent(event)
        self.layerList.clear()

        for lyr in QgsProject.instance().mapLayers().values():
            if isinstance(lyr, QgsVectorLayer) and \
                    lyr.geometryType() == QgsWkbTypes.PolygonGeometry:
                self.layerList.addItem(lyr.name())


    def __init__(self, parent=None):
        super().__init__(parent)
        super(landuse_continuityDialog, self).__init__(parent)
        self.setupUi(self)

        self.runButton.clicked.connect(self.run_analysis)

        def showEvent(self, event):
            super().showEvent(event)
            self.layerList.clear()
            for lyr in QgsProject.instance().mapLayers().values():
                if lyr.geometryType() == lyr.Polygon:
                    self.layerList.addItem(lyr.name())


        from qgis.core import QgsProject
        for lyr in QgsProject.instance().mapLayers().values():
            if lyr.geometryType() == lyr.Polygon:
                self.layerList.addItem(lyr.name())
        self.runButton.clicked.connect(self.run_analysis)

    def run_analysis(self):
        #选图层
        layer_names = [i.text() for i in self.layerList.selectedItems()]
        layers = [lyr for lyr in QgsProject.instance().mapLayers().values()
                  if lyr.name() in layer_names]

        if len(layers) < 2:
            QtWidgets.QMessageBox.warning(self, "warning", "please select at least 2 polygon layers")
            return

        thresh = self.thresholdSpin.value()

        # 禁用
        self.runButton.setEnabled(False)
        # 进度条
        self.progressBar.setValue(0)

        def _update(val: int):
            self.progressBar.setValue(val)
            # 刷新
            QgsApplication.processEvents()


        res_layer = compare_layers(
            # 算法
            layers, thresh=thresh, progress_callback=_update)


        self.progressBar.setValue(100)
        # 进度条
        self.runButton.setEnabled(True)

        QtWidgets.QMessageBox.information(
            self, "Accomplished",
            f"Analysed {len(layers)} periods.\n"
            "Fields 'persistence_count / ratio / is_persistent' were written\n"
            f"into layer:\n{res_layer.name()}"
        )



from .analysis import compare_layers
def run_analysis(self):
    layers = [QgsProject.instance().mapLayer(item.data(0))
              for item in self.listWidget.selectedItems()]
    thresh = self.doubleSpinBox.value()
    res = compare_layers(layers, thresh)

    # 导出 CSV
    path, _ = QFileDialog.getSaveFileName(self, "Save CSV", "", "CSV (*.csv)")
    if path:
        QgsVectorLayerExporter.exportLayer(
            res, path, "CSV", res.crs(), False)

    QMessageBox.information(self, "Accomplish",
        f"Analyzed {len(layers)} periods，the result layers were updated as CSV")